SELECT E.EMPNO AS EMPNO
, E.ENAME AS EMPNAME
, D.DNAME AS DEPTNAME
, REPLACE(E.HIREDATE,'/','-') AS HIREDATE
, D.LOC AS LOCATION
, ROUND(E.SAL,-2) AS SALARY
, S.GRADE AS GRADE
FROM EMP E, DEPT D, SALGRADE S
WHERE E.DEPTNO = D.DEPTNO
AND E.SAL BETWEEN LOSAL AND HISAL
AND E.SAL>(SELECT AVG(SAL) FROM EMP)
ORDER BY ROUND(E.SAL,-2) DESC, e.empno;